backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "manchester"
    label: "Manchester"
    folder: "src/content/cities/manchester"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Day", name: "day", widget: "string" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Leader", name: "leader", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "murfreesboro"
    label: "Murfreesboro"
    folder: "src/content/cities/murfreesboro"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Day", name: "day", widget: "string" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Leader", name: "leader", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "nolensville"
    label: "Nolensville"
    folder: "src/content/cities/nolensville"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Day", name: "day", widget: "string" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Leader", name: "leader", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "smyrna"
    label: "Smyrna"
    folder: "src/content/cities/smyrna"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Day", name: "day", widget: "string" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Leader", name: "leader", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
